import Head from "next/head"
import Link from "next/link"

export default function PageLayout({ children, title = "" }) {
    let TheTitle = 'newsPaper App - ' + title
    return (
        <>
        <Head>
            <title>{TheTitle}</title>
            <meta name="NewsPaper API" content="Generated by create next app, by Juan Diego Coianiz!" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <h6><Link href='/'>NewsApp</Link></h6>
        </header>
        <main>
        {children}
        </main>

        <style jsx>{`
  header {
    padding: 20px
  }`
        }</style>
    </>
    )
}